version: "3.9"
services:
  app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    build: ./datebase
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    
    env_file:
      - .env
    ports:
      - "5432:5432"
    
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d

